name: publish

on:
  push:
    branches:
      - main

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requires.txt
          pip install wheel twine
      - name: Build
        run: python setup.py bdist_wheel sdist
      - name: Check distro
        run: twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: twine upload dist/* --verbose
